version: 2

models:
  - name: stg_orders
    columns:
      - name: load_id
        description: Monotonically increasing id for the staged order changes.
        tests:
          - unique
          - not_null
      - name: order_id
        description: Order identifier in the source database.
        tests:
          - unique
          - not_null
      - name: updated_at
        description: The date when the order has been last updated.
        tests:
          - not_null
      - name: status
        description: The completion status of the order.
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
